### ISSUE TITLE
Implementation of a Motion Estimator (ME)

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [Sistemas-Multimedia/MCDWT#12]
ME is a function that inputs two frames (images): (1) a reference frame and (2) a predicted frame, and outputs a motion vectors field. For each (non-overlaping) 2D block (x,y) of the predicted frame, a ME search the (x,y) block arround the position (x,y) in the reference frame and returns the motion vector (mv[x], mv[y]) which minimizes (for example) the energy of a residue frame computed as the difference (pixel-to-pixel) between the predicted frame and the prediction frame (the resulting of a motion compensation, see issue #11).

More information is available at:

https://en.wikipedia.org/wiki/Motion_estimation
http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_video/py_lucas_kanade/py_lucas_kanade.html

**Comment by sebas5** [comment]
@Pakitoliva and @sebas5 have sent a pull request of this issue
