### ISSUE TITLE
TravisCI Integration

### ISSUE THREAD

**Issue by vicmagv** [Sistemas-Multimedia/MCDWT#17]
As a great software project, we need to have some CI pipeline to test it. (Later if we deploy it as a pypi lib or a deb package we can also config a CD to deploy them in any given repository)

For now, I think some CI is enough. I highly recommend [travisCI](https://travis-ci.org/) as it is free for open source projects (like us). This issue only makes sense once we have some tests. Furthermore,  this issue is only doable by the repo owner @vicente-gonzalez-ruiz .

This is the python docs for [travisCI docs](https://docs.travis-ci.com/user/languages/python/)

We can also add some linter to check our python stylish code!

**Comment by igj281** [comment]
@avm042 and I are working on this issue.

**Comment by vicente-gonzalez-ruiz** [comment]
I think that you are very close to finishing this issue, however, I'll wait for having all the scripts defined.
