### ISSUE TITLE
Project scaffolding and code guideline

### ISSUE THREAD

**Issue by tukaramhl** [Sistemas-Multimedia/MCDWT#2]
It's important to set up an initial scaffold for the project, even if it's a small one. This [project](https://github.com/Aaronontheweb/scaffold-py) could be used as a reference. This is also applied to the class itself, like writing the name of the functions, their arguments and return types, etc.

The other issue is the coding itself. We need to follow a code guideline to improve readability and consistence (and also to retain some form of sanity...). The official [Python code guideline](https://www.python.org/dev/peps/pep-0008/) is a good start.

**Comment by vicente-gonzalez-ruiz** [comment]
Good idea. Please, @tukaramhl, proceed.

**Comment by tukaramhl** [comment]
Done. 
[Commit reference](https://github.com/Sistemas-Multimedia/MCDWT/commit/b26135cd101a4e8dc146cd86f4e650ce129e5d79)
