### ISSUE TITLE
Read a AVI file, frame-by-frame and write it (in RAW format) to disk

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [Sistemas-Multimedia/MCDWT#3]
Supposing that the input video is in the disk, it is necessary to open the file and, for each frame in the video: (1) read it to memory, (2) decompress it, (3) write it back to disk in RAW format. At this moment, only the DWT coefficients should be put in the disk (forget any sort of header).

**Comment by manelme** [comment]
If no one minds it I'll take a look tomorrow to see how can we do that 😝

**Comment by vicente-gonzalez-ruiz** [comment]
Probably you are right. OpenCV likes the BGR format (although you can travel between color domains very easily: http://docs.opencv.org/3.1.0/df/d9d/tutorial_py_colorspaces.html). For video coding, the preferable domain is YCbCr. I use it in: https://github.com/vicente-gonzalez-ruiz/pyramids-and-wavelets

**Comment by frasco2001** [comment]
working in issue3

**Comment by manelme** [comment]
And..... It's Done

`Print('Job Well DONE!!!!')`
