### ISSUE TITLE
Compute the 1-level 2D-DWT of a frame in memory

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [Sistemas-Multimedia/MCDWT#4]
We need to transform each uncompressed (RAW) frame using the 1-level 2D-DWT. I would use [pywavelets](https://pywavelets.readthedocs.io/en/latest/regression/dwt-idwt.htm).This issue should be addressed after issue #3.

**Comment by manelme** [comment]
Done a pull request with the first try at this issue, just to let you know.
#7
