### ISSUE TITLE
Build a frame-rate duplicator

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [Sistemas-Multimedia/MCDWT#46]
If we input to iMCDWT to a sequence of pyramids where the odd pyramids (001, 003, ...) are zero, the output sequence of images will have twice the number of images of the input one and the new images will be built as an MC interpolated version of the even (000, 002, ...) images. Very useful for providing extra motion sensation to a low FPS video.

**Comment by juanjonrg** [comment]
I'll try to do it.

**Comment by vicente-gonzalez-ruiz** [comment]
Hi, as @juanjonrg has realized (thanks!), the previous algorithm does not work. We need to create the even pyramids with some LL content (not all zero). Maybe a solution can be to compute BL = (AL + CL) and tBH=0.
