### ISSUE TITLE
Implement a RGB to YCbCr (and viceversa) image converter

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [Sistemas-Multimedia/MCDWT#47]
YCbCr (sometimes called YUV, even though not being the same) is useful for coding but RGB is better for viewing. A couple of scripts that implement this functionality would be useful.

**Comment by tukaramhl** [comment]
I'm really interested in this script. I've been working on a script to convert HSL to RGB and vice versa. I'll put some code together as soon as possible.

**Comment by vicente-gonzalez-ruiz** [comment]
Thanks @tukaramhl . Please, have a look to FFMPEG if you need it.

**Comment by tukaramhl** [comment]
[Pull request #86](https://github.com/Sistemas-Multimedia/MCDWT/pull/86)

**Comment by tukaramhl** [comment]
This issue can be closed now.
