### ISSUE TITLE
Implement a quantizator

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [Sistemas-Multimedia/MCDWT#48]
As it can be seen in the output MCDWT pyramids, most of the visual information is concentrated in the LL subband. This means that if we quantize all the DWT coefficients (LL, LH, HL and HH subbands), by dividing each coefficient by a number, the so-called quantization step, the entropy should be lower (and therefore the compression ratio, higher). So, a quantizer will input the sequence of pyramids and output a quantized sequence of pyramids where each DWT coefficient (the "pixels" of a pyramid) is divided (using integer arithmetic) by a quantization step (a parameter of the quantizer). The inverse step is also necessary to be used before the use of iMCDWT to create the output (lossy) video.

**Comment by PakitOliva** [comment]
@sebas5  and @Pakitoliva are doing it
