### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [Sistemas-Multimedia/MCDWT#85]
The test script `tests/test_mcdwt.py` performs the following test:

1. Copy the image `input/000.png` to the directory `/tmp/eq` several times, generating a sequence of 5 images, all identical.

2. Run the forward and the inverse transform step of MCDWT.

The resulting images are created in `/tmp`. Among the output MCDWT images, there are several temporal images such as `predictedXXX.png`, `predictionXXX.png` and `residueXXX.png`. The predicted images are the images that we want to approximate in the ME/MC process (remember, in this case, all the images of the video are the same and therefore, the predicted images are identical and for this reason, their PNG compression produces the same number code-stream bytes), the prediction images are those that the ME/MC generates, and the residue images are the difference between the predicted and the prediction images.

As you can see, the length of `prediction001.png` is `880755` bytes and the size of `prediction003.png` is `880984`. Both lengths should be the same.

You can see the differences between both predictions running (you need Imagemagick):

```
compare prediction001.png prediction003.png diff.png
```

**Comment by vicente-gonzalez-ruiz** [comment]
Hi! I have created two scripts in a new directory called `tools`:

`show_differences.sh` -> Compute a residue image between to images. Example:

```
./show_differences.sh -1 /tmp/prediction001.png -2 /tmp/prediction003.png -o /tmp/diff.png
```

`show_histogram.sh` -> Compute the histogram of the input image. Example:

```
./show_histogram.sh -i /tmp/diff.png
```

If you run the script:

```
python test_mcdwt_2.py
 ```

You will realize (after visualizing the differences between `prediction001.png` and `prediction003.png`) that both images are almost identical (they should because the reference images are the same in both cases, see the script `test_mcdwt_2.py`). The differences are in the most right column (in pixels) of the predictions. So far, I don't know the reason :-/

**Comment by vicente-gonzalez-ruiz** [comment]
I debugged a few:

https://asciinema.org/a/4oui7t8irvvkk2tyv67pg46sr

Concluding: something wrong happens in `motion_compensation`, but only with the most right column of the image.

**Comment by juanjonrg** [comment]
I think PR #94 fixes this issue. We were wrongly using the BORDER_TRANSPARENT option to extrapolate pixels that fell outside of the image. That's why only the pixels in the bottom and right borders were affected.

Please test it 😄

**Comment by vicente-gonzalez-ruiz** [comment]
Sure it works ... thanks @juanjonrg !

**Comment by vicente-gonzalez-ruiz** [comment]
Yes, works fine :-)
